home/urls.py
from django.urls import path
from login.views import loginView, signupView
from .views import index

urlpatterns = [
    path('', index, name='homepage'),
    path('login', loginView, name='loginpage'),
    path('signup', signupView, name='signuppage'),
]

tms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import index, profileView, ProcessBooking, GetDestinations
from home.views import SearchView, SelectionView, BookingView
from login.views import loginView, signupView, logoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='homepage'),
    path('login', loginView, name='loginpage'),
    path('signup', signupView, name='signuppage'),
    path('profile', profileView, name='profilepage'),
    path('search', SearchView.as_view(), name='searchpage'),
    path('selection', SelectionView.as_view(), name='selectionpage'),
    path('booking', BookingView.as_view(), name='bookingpage'),
    path('ajax/processbooking', ProcessBooking, name='processbooking'),
    path('ajax/getdestinations', GetDestinations, name='getdestinations'),
    path('logout', logoutView, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from login.models import User
# Create your models here.


class Destination(models.Model):
    name = models.CharField(max_length=64, unique=True, null=False)
    description = models.TextField(blank=True)
    background = models.ImageField(upload_to='background_images')

    def __str__(self):
        return str(self.name)


class Lodging(models.Model):
    name = models.CharField(max_length=64, unique=True, null=False)
    description = models.TextField(blank=True)
    background = models.ImageField(upload_to='background_images')
    address = models.CharField(max_length=128, unique=False, blank=False)
    contactno = models.CharField(max_length=20)
    website = models.URLField(blank=True)
    place = models.ForeignKey(
        Destination, on_delete=models.PROTECT, related_name='lodgings')

    def __str__(self):
        return str(self.name)


class Room(models.Model):
    name = models.CharField(max_length=64, unique=False, null=False)
    image = models.ImageField(upload_to='room_images')
    capacity = models.IntegerField(null=False)
    size = models.IntegerField(null=False)
    features = models.TextField(blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, blank=False)
    host = models.ForeignKey(
        Lodging, on_delete=models.PROTECT, related_name='rooms')

    def __str__(self):
        return str(self.id)
        # return "%s (%s)" % (
        #     str(self.id),
        #     ", ".join(str(booking.id) for booking in self.bookings.all()),
        # )


class Booking(models.Model):
    startdate = models.DateField(null=False)
    enddate = models.DateField(null=False)
    no_of_people = models.IntegerField(null=False)
    no_of_rooms = models.IntegerField(null=False)
    total_cost = models.DecimalField(max_digits=12, decimal_places=2, blank=False)
    room = models.ForeignKey(
        Room, on_delete=models.PROTECT, related_name='bookings', null=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='reservation_holder', null=False)

    def __str__(self):
        return str(self.id)

# class Package(models.Model):

home/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={
        'name': 'search', 'placeholder': 'Search...', 'class': 'searchfield'}),
        label='')


class FilterForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(
        attrs={'placeholder': 'Arrival Date', 'class': 'filterfield', 'autocomplete': 'off'}),
        label='')
    end_date = forms.DateField(widget=forms.DateInput(
        attrs={'placeholder': 'Departure Date', 'class': 'filterfield', 'autocomplete': 'off'}),
        label='')
    capacity = forms.IntegerField(widget=forms.NumberInput(
        attrs={'placeholder': 'Person(s)', 'class': 'filterfield', 'autocomplete': 'off'}), label='')

home/views.py
from django.shortcuts import render, reverse, render_to_response
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.core import serializers
from .models import Destination, Lodging, Room, Booking
from login.models import User, UserInfo
from .forms import SearchForm, FilterForm
import datetime
import math
import json

# Create your views here.


def index(request):
    if request.method == 'POST':

        search_form = SearchForm(request.POST)

        if search_form.is_valid():
            search_string = search_form.cleaned_data['search']
            try:
                place = Destination.objects.get(name__icontains=search_string)
            except Destination.DoesNotExist:
                error_desc = "Destination does not exist."
                error_desc += "Are you sure you entered the correct spelling?"
                error_desc += "If you think this is a mistake,"
                error_desc += " please submit a bug report."
                search_form.add_error(
                    'search', error_desc)
                return render(request, 'home/index.html',
                              {'form': search_form})
            if place:
                request.session['place'] = place.name
                return HttpResponseRedirect(reverse('searchpage'))

        return render(request, 'home/index.html', {'form': search_form})
    else:
        return render(request, 'home/index.html', {'form': SearchForm()})


@login_required
def profileView(request):
    return HttpResponse('Profile page will be here')


@csrf_exempt
def ProcessBooking(request):
    data = json.loads(request.body)
    user = request.user
    room = Room.objects.get(pk=data["roomid"])
    startdate = datetime.datetime.strptime(data["startdate"], "%Y-%m-%dT%H:%M:%S.%fZ")
    enddate = datetime.datetime.strptime(data["enddate"], "%Y-%m-%dT%H:%M:%S.%fZ")
    no_of_people = int(data["no_of_people"])
    no_of_rooms = int(data["no_of_rooms"])
    total_cost = float(data["total_cost"])
    booking_req = Booking(startdate=startdate, enddate=enddate, total_cost=total_cost,
    no_of_people=no_of_people, no_of_rooms=no_of_rooms, room=room, user=user)    
    booking_req.save()
    for key in data:
        print("key: "+ key)
        print("value: " + str(data[key]))

    data = True
    return JsonResponse({'result': data})


@csrf_exempt
def GetDestinations(request):
    destinations = Destination.objects.all()

    location_object = []

    for dest in destinations:
        location_object.append(dict([("name", dest.name)]))


    return JsonResponse(location_object, safe=False)
# class SearchView(TemplateView):
#     # model = Lodging
#     template_name = 'home/search.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         # add extra context here
#         if 'place' in self.request.session:
#             place = Destination.objects.get(name=self.request.session['place']) # noqa: E501
#             context['place_name'] = place.name
#             context['place_description'] = place.description
#             context['filter_form'] = FilterForm()

#         return context

#     def post(self, request, *args, **kwargs):
#         context = self.get_context_data(**kwargs)
#         filter_form = FilterForm(request.POST)
#         if filter_form.is_valid():
#             return HttpResponseRedirect(reverse('selectionpage'))

#         return super(TemplateView, self).render_to_response(context)


# add custom decorator to access the page.
# If place name is not set in session, redirect to home page.
# IF SESSION VARIABLE NAMES ARE CHANGED, UPDATE DECORATORS ACCORDINGLY!
class SearchView(FormView):
    form_class = FilterForm
    template_name = 'home/search.html'
    success_url = '/selection'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # add extra context here
        if 'place' in self.request.session:
            place = Destination.objects.get(name=self.request.session['place'])
            context['place_name'] = place.name
            context['place_description'] = place.description
            context['place_background'] = place.background
            context['filter_form'] = FilterForm()

        return context

    def form_valid(self, form):
        self.request.session['start_date'] = str(
            form.cleaned_data['start_date'])
        self.request.session['end_date'] = str(form.cleaned_data['end_date'])
        self.request.session['people'] = str(form.cleaned_data['capacity'])
        self.request.session['stay_days'] = str(
            form.cleaned_data['end_date'].day - form.cleaned_data['start_date'].day)
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


# add custom decorator to access the page.
# If filter details are not set in session, redirect to search page.
# IF SESSION VARIABLE NAMES ARE CHANGED, UPDATE DECORATORS ACCORDINGLY!
class SelectionView(ListView):
    model = Room
    # queryset = Room.objects.exclude(bookings__startdate__gte=datetime.date(2018, 1, 2), bookings__enddate__lte=datetime.date(2018, 1, 4))
    template_name = 'home/selection.html'
    context_object_name = 'rooms'

    
    def dispatch(self, request, *args, **kwargs):
        try:
            startdate = self.request.session['start_date']
            enddate = self.request.session['end_date']
        except KeyError:
            return HttpResponseRedirect(reverse('searchpage'))

        startdate = datetime.datetime.strptime(self.request.session['start_date'], '%Y-%m-%d').date() 
        enddate = datetime.datetime.strptime(self.request.session['end_date'], '%Y-%m-%d').date()

        if startdate > enddate:
            return HttpResponseRedirect(reverse('searchpage'))
        
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = self.model.objects.all().prefetch_related('bookings')

        startdate = datetime.datetime.strptime(self.request.session['start_date'], '%Y-%m-%d').date() 
        enddate = datetime.datetime.strptime(self.request.session['end_date'], '%Y-%m-%d').date()

        for booking in Booking.objects.all():
            # check if both dates are inside any bookings. If a matching booking is found for any room, exclude that room
            if (startdate >= booking.startdate and startdate <= booking.enddate) or (enddate >= booking.startdate and enddate <=booking.enddate):
                queryset = queryset.exclude(bookings__id=booking.id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def post(self, request, *args, **kwargs):
        room_id = request.POST.get('room_id')
        request.session['room_id'] = room_id
        return HttpResponseRedirect(reverse('bookingpage'))
        # return HttpResponse(
        # 'Booking page will be here. Room ID: {}'.format(room_id))


class BookingView(LoginRequiredMixin, TemplateView):
    template_name = 'home/booking.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['user'] = self.request.user
        context['no_of_people'] = self.request.session.get('people')

        room_obj = Room.objects.get(
            id=int(self.request.session.get('room_id')))

        context['room'] = room_obj
        context['people_no'] = self.request.session.get('people')

        room_price = room_obj.price
        room_required = (math.ceil(int(self.request.session.get('people')
                                       ) / int(room_obj.capacity)))

        room_cost = (int(room_price) * int(room_required) *
                     int(self.request.session.get('stay_days')))

        context['stay_days'] = self.request.session.get('stay_days')
        context['room_price'] = room_price
        context['room_required'] = room_required
        context['room_cost'] = room_cost

        context['start_date'] = self.request.session.get('start_date')
        context['end_date'] = self.request.session.get('end_date')

        # context['session_keys'] = [key for key in self.request.session.keys()]
        # context['session_data'] = [self.request.session[key]
        #                            for key in self.request.session.keys()]
        return context

templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home - BucketList Travels</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/home.css' %}" />
    {% block style %}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css">
    <style>
        body {
            background-image: url("{% static 'images/bg.jpg' %}");
            /* background-image: url('../images/bg.jpg'); */
            background-color: #747474;
        }
    </style>
    {% endblock %}


</head>

<body>
    <div>
        {% if request.path == "/" %}
        <a href="/"><img src="{% static 'images/logo.png' %}" style="width:auto;height: auto;"
                alt="Bucket List Travel Logo."></a>
        {% else %}
        <a href="/"><img src="{% static 'images/logo.png' %}" style="width:250px;height: auto;"
                alt="Bucket List Travel Logo."></a>
        {% endif %}
        <ul>
            <li><a href="{% url 'homepage' %}">Home</a></li>
            <li><a href="{% url 'homepage' %}">Places</a></li>
            <li><a href="{% url 'homepage' %}">Contact</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'profilepage' %}">Profile</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'loginpage' %}">Login</a></li>
            <li><a href="{% url 'signuppage' %}">Sign up</a></li>
            {% endif %}

        </ul>
    </div>

    {% block content %}
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>


    {% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js"></script>


    <script>
    
    // var list = null;

    var eaccode = function() {
        var options = {
        url: function(phrase) {
            return "ajax/getdestinations"
        },

        getValue: function(element){
            return element.name
        },

        ajaxSettings: {
            dataType: "json",
            method: "POST",
            data: {
                dataType: "json"
            }
        },

        preparePostData: function(data) {
            data.phrase = $("#id_search").val();
            return data;
        },

        requestDelay: 400,

        list: {
            match: {
                enabled: true
                }
            }
        };

        $("#id_search").easyAutocomplete(options);

    };

    var populateList = function() {
        // $.ajax({
        //     url: 'ajax/getdestinations',
        //     type: "POST",
        //     contentType: "application/json; charset=utf-8",
        //     cache: false,
        //     success: function(data) {
        //         list = data;
        //         eaccode();
        //     },
        //     error: function(jqxhr, status, error) {
        //         alert(status + ": " + error);
        //     }
        // });
        eaccode();
    }

    $(document).ready(function(){
        populateList();
    });

    </script>

    {% endblock %}
</body>

</html>

templates/home/booking.html
{% extends 'home/base.html' %}


{% block style %}

<style>
    body {
        background-color: #3f3f3f;
    }

    p,
    h1,
    h2,
    h3 {
        color: white;
    }
</style>

{% endblock style %}



{% block content %}
<!-- Right now it's printing the session content,
     which will be used to create this page's content -->
<!-- <div class="temp">
    {% for key in session_keys %}
    {{ key }}
    {% empty %}
    <p> No session keys available </p>
    {% endfor %}
    <p></p>
    {% for data in session_data %}
    {{ data }}
    {% empty %}
    <p> No session data available </p>
    {% endfor %}
</div> -->

<div class="container container-fluid">
    <form method="POST">
        {% csrf_token %}
        <div>
            <h1>Booking Details: </h1>
            <div>
                <h2>Room Details: </h2>
                <p> {{room.name}} </p>
                <p> {{room.host.name}} </p>
                <p> Capacity: {{room.capacity}} </p>
                <p> Arrival Date: <span id="startdate"> {{start_date}} </span></p>
                <p> Departure Date: <span id="enddate"> {{end_date}} </span> </p>
            </div>
            <div>
                <h2>Services: </h2>
            </div>
        </div>

        <div>
            <h2>Your Information </h2>
            <p>{{user.first_name}} {{user.last_name}}</p>
            <p>{{ user.email }}</p>
            <p>{{ user.userinfo.contactno }}</p>
        </div>

        <div>
            <h2>Cost Calculation: </h2>
            <p>Price: {{ room_price }} BDT per night </p>
            <p>Number of Days to Stay: {{ stay_days }} </p>
            <p>Number of Rooms Required: {{ room_required }} </p>
            <h3>Total: {{ room_cost }} BDT</h3>
        </div>
        <div>
            <h2>Payment </h2>
        </div>
        <div>
            <button type="button" value="Confirm Booking" class="btn" id="process_booking_btn">
        </div>
    </form>
</div>

{% endblock %}


{% block scripts %}
<script type="text/javascript">
    var processBooking = function () {
        var data = {
            roomid: {{room.id}},
            startdate: new Date($("#startdate").text()),
            enddate: new Date($("#enddate").text()),
            no_of_people: {{ people_no }},
            no_of_rooms: {{ room_required }},
            total_cost: {{ room_cost }}
        }
        
        $.ajax({
            url: "ajax/processbooking",
            data: JSON.stringify(data),
            type: "POST",
            contentType: "application/json; charset=utf-8",
            cache: false,
            success: function(data) {
                alert("Success!");
            },
            error: function(jqxhr, status, error) {
                alert(status + ": " + error);
            }
        });
    }

    $(document).ready(function () {
        $("#process_booking_btn").click(function(){
            processBooking();
        });


    });
</script>


{% endblock %}

templates/home/homebase.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home - BucketList Travels</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/home.css' %}" />

</head>

<body>
    <div>
        <img src="{% static 'images/logo.png' %}" style="width:auto;height: auto;" alt="Bucket List Travel Logo.">

        <ul>
            <li><a href="{% url 'homepage' %}">Home</a></li>
            <li><a href="{% url 'homepage' %}">Places</a></li>
            <li><a href="{% url 'homepage' %}">Contact</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'profilepage' %}">Profile</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'loginpage' %}">Login</a></li>
            <li><a href="{% url 'signuppage' %}">Sign up</a></li>
            {% endif %}

        </ul>
    </div>

    {% block search %}
    <div class="srcbar">
        <form method="POST">
            <input type="text" name="search" placeholder="Search...">
            <button type="submit">
                <b>GO!</b>
            </button>
        </form>

    </div>
    {% endblock %}

</body>

</html>

templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}


<div class="srcbar">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <input type="text" name="search" placeholder="Search..."> -->
        <button type="submit">
            <b>GO!</b>
        </button>
    </form>

</div>

{% endblock %}

templates/home/search.html
{% extends 'home/base.html' %}



{% block style %}

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.8.0/css/pikaday.min.css">

<style>


    body{
        background: 
            linear-gradient(
            rgba(0, 0, 0, 0.7), 
            rgba(0, 0, 0, 0.3)
            ),
            url(media/{{place_background}});
            background-attachment: fixed;
        }

    h1{
        font-size: 36pt;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color: white;
    }

    h2{
        font-size: 24pt;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: white;
    }

    h3{
        font-size: 18pt;
        color: white;
        text-align: justify;
    }

    #filterIns{
        color: white;
        margin-bottom: 20px;
    }
	
    #description{
        width: 600px;
        height: auto;
        margin-left: 15%;
        float: left;
    }

    #filter{
        box-sizing: border-box;
        width: 550px;
        height: auto;
        float: right;
        margin-right: 15%;
        background-color:  rgba(0, 0, 0, .4);
        padding: 0px 50px 100px;
        
    }




/* EXPERIMENTAL

    #filter{
        width: 600px;
        height: auto;
        float: right;
        margin-right: 15%;
        background-color: black;
        box-sizing: border-box;
        padding: 25px;  
    }

    .filterfield{
        margin-left: 50%;
        width: 70%;
        transform: translate(-50%);
        margin-top: 20px;
    }

    input[type=submit]{
        margin-left: 50%;
        width: 100%;
        transform: translate(-50%);
        margin-top: 20px;
    }
    

    */

    form input.filterfield{
        width: 100%;
        box-sizing: border-box;
        padding: 10px 50px 10px 50px;
        /* margin-left: 50%; */
        /* transform: translate(-50%); */
        border: 0px solid black;
        border-radius: 4px;
        font-size: 20px;
        box-shadow: 0px 0px 10px 0px #333333;
        margin-top: 10px;
        font-size: 20px;
     
        /* color: white; */

    }
#searchButton{
    background-color:#00a26f;
    margin-top: 30px;
}





</style>
{% endblock %}




{% block content %}




<div class="container" id="description">
    <h1> {{ place_name }} </h1>
    <hr>

    <h3> {{ place_description }} </h3>



</div>

<div class="container" id="filter">

    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endif %}

    <form method="post">
        <h2 id="filterIns">Enter Booking Details </h2>
        <hr>
        {% csrf_token %}
        <!-- {{ filter_form.as_p }} -->

        {% for field in filter_form %}
        <div class="fieldWrapper">
            {{ field.error }}
            {{ field }}
            <!-- add datepicker here -->
        </div>
        {% endfor %}

        <input id="searchButton" class="filterfield" type="submit" value="Search">
    </form>



</div>
{% endblock content %}


{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.8.0/pikaday.min.js"></script>

<script>


$(document).ready(function(){
    
    var startdatePicker = new Pikaday({ field: $('#id_start_date')[0], minDate: new Date() });

    var enddatePicker = new Pikaday({ field: $('#id_end_date')[0], minDate: new Date() });

    startdatePicker.toString('YYYY-MM-DD')
    enddatePicker.toString('YYYY-MM-DD')

});
</script>


{% endblock %}

templates/home/selection.html
{% extends 'home/base.html' %}





{% block style %}

<style>


    p {
        color: white;
        margin: auto;
    }
    body {
        background-color: #535759;
    }



.bookbuttons{
        display: block;
        float: left;

        font-size: 20px;
		padding: 10px 20px 10px 20px;

		border: 1px solid #00a26f;

		color: white;
		
        width: 100%;
        margin-top: 20px;
     


	}


#booknow{
    background-color:#00a26f;
   
}

#details{

    box-sizing: border-box;

    /* background-color: rgba(255, 255, 255, .5);
    border:4px solid white; */
    background-color: rgba(49, 50, 51, 0.5);
    border: 4px solid rgb(80, 80, 80);
    color: white;
  

}


.thumbnail{
    margin-left: 50%;
    transform: translate(-50%);
    border: 4px solid transparent;
}

.thumbnaildetails{
    margin-top: 20px;
    text-align: left;
    margin-left: 20%;
    font-size: 15pt;
    
}


.thumbnailtitle{
    color: white;
    text-align: center;
    font-size: 30pt;
    margin-top: 20  px;

}

</style>

{% endblock %}




{% block content %}
<div class="container-fluid">
    <div class="grid-container">
        <div class="row">
            {% for room in rooms %}
            {% if forloop.counter0|divisibleby:3 and forloop.counter0 > 0 %}
        </div>
        <div class="row">
            {% endif %}
            <div class="col">
                <div class="grid-item">
                    <div class="img-container">
                        <img class="thumbnail" src="/media/{{ room.image }}" alt="Image" width="360" height="240">
                    </div>
                    <h1 class="thumbnailtitle"> {{ room.name }} </h1>
                    <hr>
                    <div class="thumbnaildetails">
                        <p>&#9830 {{ room.host.name }}</p>
                        <p>&#9830 {{ room.size }} sq-ft </p>
                        <p>&#9830 {{ room.capacity }} person</p>
                        <p> &#9830 {{ room.price }} per night </p>
                    </div>
                    <div>
                        <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="room_id" value="{{ room.id }}">
                            <button id="details" class="bookbuttons"> Details </button>
                            <button id="booknow" class="bookbuttons" type="submit"> Book </button>
                        </form>
                    </div>
                </div>
            </div>



            {% empty %}
            <h3> Sorry, system couldn't find any result matching the search criteria </h3>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}